# For full config options, check the docs:
#    docs.serverless.com


service: mestrado # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

custom:
  dlqtopic: "${self:service}-${opt:stage, self:provider.stage}-failed"
  inputtopic: "${self:service}-${opt:stage, self:provider.stage}-input"
  sourceBucket: "${self:service}-${opt:stage, self:provider.stage}-phyml"

provider:
  name: aws
#  stage: dev
  region: us-east-2
  runtime: python3.6

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.sourceBucket}/*"
    - Effect: Allow
      Action:
        - sns:*
      Resource: "*"
    - Effect: Allow
      Action:
        - batch:SubmitJob
      Resource: "arn:aws:batch:#{AWS::Region}:#{AWS::AccountId}:*"

package:
  individually: true
  exclude:
    - "*/**"

functions:

  modeltest:
    memorySize: 128
    timeout: 30
    handler: handler.execute
    onError: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.dlqtopic}"
    events:
      - sns: ${self:custom.inputtopic}
    package:
      include:
        - "lib/phyml"
        - aws.py
        - handler.py

  dlq-forwarder:
    memorySize: 128
    timeout: 5
    handler: forwarder.execute
    events:
      - sns: ${self:custom.dlqtopic}
    package:
      # We're including this file so it will be in the final package of this function only
      include:
        - forwarder.py

