# For full config options, check the docs:
#    docs.serverless.com


service: mestrado # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

custom:
  dlq: "${self:service}-${opt:stage, self:provider.stage}-failed"
  inputqueue: "${self:service}-${opt:stage, self:provider.stage}-inputqueue"
  sourceBucket: "${self:service}-${opt:stage, self:provider.stage}-phyml-input"

provider:
  name: aws
#  stage: dev
  region: us-east-2
  runtime: python3.6

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.sourceBucket}/*"
    - Effect: Allow
      Action:
        - sns:*
      Resource: "*"
    - Effect: Allow
      Action:
        - batch:SubmitJob
      Resource: "arn:aws:batch:#{AWS::Region}:#{AWS::AccountId}:*"

package:
  exclude:
    - .vscode/**
    - .git/**
    - node_modules/**
    - "*.md"
    - "*.json"

functions:

  modeltest:
    memorySize: 128
    timeout: 30
    handler: handler.execute
    onError: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.dlq}"
    events:
      - sns: ${self:custom.inputqueue}

  dlq-forwarder:
    memorySize: 128
    timeout: 5
    handler: forwarder.execute
    events:
      - sns: ${self:custom.dlq}

