# For full config options, check the docs:
#    docs.serverless.com


service: mestrado # NOTE: update this with your service name

# PARAMS
custom:
  inputqueue: "${self:service}-${self:provider.stage}-inputqueue"

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
  region: us-east-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "SNS:Publish"
      Resource: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.inputqueue}" ] ]  }

functions:
  modeltest:
    memorySize: 128
    handler: handler.execute
    events:
      - sns: ${self:custom.inputqueue}


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
