# For full config options, check the docs:
#    docs.serverless.com


service: mestrado # NOTE: update this with your service name

# PARAMS
custom:
  inputqueue: "${self:service}-${self:provider.stage}-inputqueue"
  sourceBucket: mestrado-dev-phyml-input

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
  region: us-east-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "SNS:Publish"
#      Resource: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.inputqueue}" ] ]  }
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.sourceBucket}/*"


functions:
  modeltest:
    memorySize: 128
    handler: handler.execute
    events:
      - sns: ${self:custom.inputqueue}


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    phyml:
#      Type: AWS::S3::Bucket
#      Properties: 
#        BucketName: "${self:service}-${self:provider.stage}-phyml-input"
#  Outputs:
#     phymlBucket:
#       Description: "S3 bucket for phyml input data"
#       Value: { Fn::GetAtt : [ phyml, Arn ] }

